TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += nEDCommon.db
DB += OccPortDriver.db
DB += DiscoverPlugin.db
DB += DspPlugin_v63.db
DB += DspPlugin_v64.db
DB += FemPlugin_v32.db
DB += FemPlugin_v35.db
DB += FemPlugin_v36.db
DB += AcpcFemPlugin_v22.db
DB += RocPlugin_v51.db
DB += RocPlugin_v52.db
DB += RocPlugin_v54.db
DB += RocPlugin_v56.db
DB += RocHv.template
DB += ROCHV.db
DB += ROCHVSumBL16b.db
DB += DumpPlugin.db
DB += StatPlugin.db
DB += RtdlPlugin.db
DB += AdaraPlugin.db
DB += CmdDispatcherPlugin.db
DB += DebugPlugin.db
DB += FlatFieldPlugin.db
DB += ProxyPlugin.db
DB += PixelMapPlugin.db
DB += RocPvaPlugin.db
DB += AcpcPvaPlugin.db
DB += GlobalConG.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
